allOf:
  - $ref: "./SpConfigJob.yaml"
  - type: object
    required:
      - completed
      - message
    properties:
      message:
        type: string
        description: This message contains additional information about the overall status of the job.
        example: "Download import results for details."
      completed:
        type: string
        format: 'date-time'
        description: The time the job was completed.
        example: "2021-05-11T22:23:16Z"