get:
  operationId: getCampaignReportsConfig
  tags:
    - Certification Campaigns
  summary: Get Campaign Reports Configuration
  deprecated: true
  description: >- 
    Fetches configuration for campaign reports. Currently it includes only one element - identity attributes defined as custom report columns.

    Requires roles of CERT_ADMIN and ORG_ADMIN.

  security:
    - UserContextAuth: [ idn:campaign-reports-config:read ]
  responses:
    '200':
      description: Campaign Report Configuration
      content:
        application/json:
          schema:
            $ref: '../schemas/CampaignReportsConfig.yaml'
    '400':
      $ref: '../../v3/responses/400.yaml'
    '401':
      $ref: '../../v3/responses/401.yaml'
    '403':
      $ref: '../../v3/responses/403.yaml'
    '429':
      $ref: '../../v3/responses/429.yaml'
    '500':
      $ref: '../../v3/responses/500.yaml'
put:
  operationId: setCampaignReportsConfig
  tags:
    - Certification Campaigns
  summary: Set Campaign Reports Configuration
  deprecated: true
  description: >- 
    Overwrites configuration for campaign reports.

    Requires roles CERT_ADMIN and ORG_ADMIN.

  security:
    - UserContextAuth: [ idn:campaign-reports-config:write ]
  requestBody:
    required: true
    description: Campaign Report Configuration
    content:
      application/json:
        schema:
          $ref: '../schemas/CampaignReportsConfig.yaml'
  responses:
    '200':
      description: The persisted Campaign Report Configuration
      content:
        application/json:
          schema:
            $ref: '../schemas/CampaignReportsConfig.yaml'
    '400':
      $ref: '../../v3/responses/400.yaml'
    '401':
      $ref: '../../v3/responses/401.yaml'
    '403':
      $ref: '../../v3/responses/403.yaml'
    '429':
      $ref: '../../v3/responses/429.yaml'
    '500':
      $ref: '../../v3/responses/500.yaml'
