get:
  operationId: getReassignmentConfigTypes
  tags:
    - Work Reassignment
  summary: List Reassignment Config Types
  description: >-
    Gets a collection of types which are available in the Reassignment Configuration UI.
  security:
    - UserContextAuth: [idn:reassignment-configuration:read]
  responses:
    '200':
      description: List of Reassignment Configuration Types
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../schemas/work-reassignment/ConfigType.yaml'
    '400':
      $ref: '../../v3/responses/400.yaml'
    '401':
      $ref: '../../v3/responses/401.yaml'
    '403':
      $ref: '../../v3/responses/403.yaml'
    '429':
      $ref: '../../v3/responses/429.yaml'
    '500':
      $ref: '../../v3/responses/500.yaml'