get:
  operationId: getPotentialRoleApplications
  summary: Retrieves the applications of a potential role for a role mining session
  tags:
    - IAI Role Mining
  description: >-
    This method returns the applications of a potential role for a role mining session.
  parameters:
    - in: path
      name: sessionId
      schema:
        type: string
      required: true
      description: The role mining session id
      example: 8c190e67-87aa-4ed9-a90b-d9d5344523fb
    - in: path
      name: potentialRoleId
      schema:
        type: string
      required: true
      description: A potential role id in a role mining session
      example: 8c190e67-87aa-4ed9-a90b-d9d5344523fb
    - $ref: '../../v3/parameters/offset.yaml'
    - $ref: '../../v3/parameters/limit.yaml'
    - $ref: '../../v3/parameters/count.yaml'
  responses:
    '200':
      description: Succeeded. Returns a list of potential roles for a role mining session.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../schemas/RoleMiningPotentialRoleApplication.yaml'
    '400':
      $ref: '../../v3/responses/400.yaml'
    '401':
      $ref: '../../v3/responses/401.yaml'
    '403':
      $ref: '../../v3/responses/403.yaml'
    '500':
      $ref: '../../v3/responses/500.yaml'
